#!/bin/sh

#!/usr/bin/env bash
export SCRIPTPATH="$(
	cd "$(dirname "$0")"
	pwd -P
)"
$SCRIPTPATH/down

# setup theme
$SCRIPTPATH/themes/win-xp/up

# android connection
dbus-daemon --session --address="unix:path=$XDG_RUNTIME_DIR/bus" &
kdeconnect-indicator &

# corsair keyboard control
sudo ckb-next-daemon &
ckb-next -b &

# clipboard manager
copyq --start-server &

# redshift
redshift-gtk &

# remote desktop
sudo sunshine &

# emojis window
emote &

killall flameshot
flameshot &

disown
