format = "[░▒▓](#a3aed2)[  ](bg:#a3aed2 fg:#090c0c)[](bg:#769ff0 fg:#a3aed2)$directory[](fg:#769ff0 bg:#394260)$git_branch$git_status[](fg:#394260 bg:#212736)$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$vlang$vagrant$zig$nix_shell$conda$meson$spack$memory_usage$env_var$crystal$custom$sudo$cmd_duration$jobs$battery[](fg:#212736 bg:#1d2230)$time[ ](fg:#1d2230)\n$character"
[c]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "bg:#212736"
symbol = ""

[cmd_duration]
format = "[took [$duration](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
format = "[ $path ]($style)"
read_only = " 󰌾"
style = "fg:#e3e5e5 bg:#769ff0"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
format = "[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)"
style = "b:#394260"
symbol = ""

[git_status]
format = "[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)"
style = "b:#394260"

[golang]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = ""

[julia]
symbol = " "

[lua]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = ""

[memory_usage]
symbol = "󰍛 "

[meson]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = ""

[nodejs]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = ""

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
openSUSE = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = ""

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)"
style = "b:#212736"
symbol = ""

[scala]
symbol = " "

[time]
disabled = false
format = "[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)"
style = "bg:#1d2230"
time_format = "%R"
